/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import cronopioproject.MyConnection;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public final class PuntoVenta extends javax.swing.JFrame {

    public static String nombre;
    DefaultTableModel detalle_factura;
    Object[] detalle = new Object[5];

    /**
     * Creates new form PuntoVenta
     */
    public PuntoVenta() {

        initComponents();
        generarIdFact();
        SetFacturaID();
        this.detalle_factura = (DefaultTableModel) tbl_detalle.getModel();
        txt_vendedor_f.setText(nombre);
        Mostrardatos("");
        Mostrartiempo();

    }

    public void Mostrartiempo() {
        clase_tiempo_actual tiempo = new clase_tiempo_actual();
        lbl_no_f1.setText(tiempo.fechacomp);

    }

    public final void Mostrardatos(String valor) {
        //Funcion para llenar la jtable de Usuarios desde la BD

        RefrescarTabla();
        detalle_factura.addColumn("Id factura");
        detalle_factura.addColumn("Nombre producto");
        detalle_factura.addColumn("Precio unitario");
        detalle_factura.addColumn("Cantidad");
        detalle_factura.addColumn("Importe");

        this.tbl_detalle.setModel(detalle_factura);

    }

    public void RefrescarTabla() {
        //Funcion encargada de Refrescar la tabla utilizando Revalidate
        try {
            detalle_factura.setColumnCount(0);
            detalle_factura.setRowCount(0);
            tbl_detalle.revalidate();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error " + ex);
        }
    }

    final void SetFacturaID() {
        String old_id_fact = lbl_no_f.getText();
        int sum_id_fact = Integer.parseInt(old_id_fact) + 1;
        String sum_string = String.valueOf(sum_id_fact);
        lbl_no_f.setText(sum_string);
    }

    final void generarIdFact() {
        String serie;
        serie = SetIdFact();
        if (serie == null) {

            lbl_no_f.setText("0");

        } else {
            int incrementar = Integer.parseInt(serie);

            lbl_no_f.setText(String.valueOf(incrementar));
        }

    }

    public String SetIdFact() {
        String serie = "";
        String sql = "SELECT MAX(idFactura) FROM factura";

        try {

            MyConnection cc = new MyConnection();
            Connection con = MyConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs;
            rs = ps.executeQuery();

            while (rs.next()) {
                serie = rs.getString(1);

            }

        } catch (SQLException ex) {
            Logger.getLogger(PuntoVenta.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }

        return serie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_cliente_f = new javax.swing.JLabel();
        lbl_producto_f = new javax.swing.JLabel();
        lbl_cantidad_f = new javax.swing.JLabel();
        lbl_precio_f = new javax.swing.JLabel();
        lbl_vendedor_f = new javax.swing.JLabel();
        lbl_rnc_f = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        txt_cliente_f = new javax.swing.JTextField();
        txt_producto_f = new javax.swing.JTextField();
        txt_cantidad_f = new javax.swing.JTextField();
        txt_precio_f = new javax.swing.JTextField();
        txt_vendedor_f = new javax.swing.JTextField();
        txt_rnc_f = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_buscar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_no_factura = new javax.swing.JLabel();
        lbl_no_f = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detalle = new javax.swing.JTable();
        lbl_total = new javax.swing.JLabel();
        txt_total_f = new javax.swing.JTextField();
        btn_finalizar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbl_no_factura1 = new javax.swing.JLabel();
        lbl_no_f1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Facturación");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        lbl_cliente_f.setText("Cliente:");

        lbl_producto_f.setText("Producto:");

        lbl_cantidad_f.setText("Cantidad:");

        lbl_precio_f.setText("Precio:");

        lbl_vendedor_f.setText("Vendedor:");

        lbl_rnc_f.setText("RNC:");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        txt_producto_f.setEditable(false);

        txt_cantidad_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidad_fActionPerformed(evt);
            }
        });

        txt_precio_f.setEditable(false);

        txt_rnc_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rnc_fActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar producto");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_buscar1.setText("Buscar empleado");
        btn_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_cliente_f, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_producto_f, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_producto_f)
                            .addComponent(txt_cliente_f)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_vendedor_f)
                            .addComponent(lbl_precio_f)
                            .addComponent(lbl_cantidad_f)
                            .addComponent(lbl_rnc_f, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_precio_f)
                            .addComponent(txt_cantidad_f)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_vendedor_f, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_rnc_f))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar)
                    .addComponent(btn_buscar1))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cliente_f, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cliente_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(153, 153, 153))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_producto_f)
                            .addComponent(txt_producto_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cantidad_f)
                            .addComponent(txt_cantidad_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_precio_f)
                            .addComponent(txt_precio_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_vendedor_f)
                            .addComponent(txt_vendedor_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_rnc_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_rnc_f))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        lbl_no_factura.setText("No.Factura:");

        lbl_no_f.setText("0");
        lbl_no_f.setToolTipText("");
        lbl_no_f.setAlignmentX(4.0F);
        lbl_no_f.setAlignmentY(4.0F);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_no_f, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_no_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_no_factura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_no_f)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tbl_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_detalle);

        lbl_total.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_total.setText("Total:");

        txt_total_f.setEditable(false);

        btn_finalizar.setText("Finalizar");
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        lbl_no_factura1.setText("Fecha:");

        lbl_no_f1.setText("0000/00/00");
        lbl_no_f1.setToolTipText("");
        lbl_no_f1.setAlignmentX(4.0F);
        lbl_no_f1.setAlignmentY(4.0F);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_no_factura1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_no_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_no_factura1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_no_f1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(lbl_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_f, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(223, 223, 223)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total)
                    .addComponent(txt_total_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_finalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public void LimpiarDatosProd() {
        //Funcion para limpiar los text field existentes
        try {
            txt_producto_f.setText("");
            txt_cantidad_f.setText("");
            txt_precio_f.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error " + ex);
        }
    }

    public void imprimir() {
        Connection cn = MyConnection.getConnection();
        try {
            int txtFac;
            txtFac = Integer.parseInt(lbl_no_f.getText());
            JasperReport jr = (JasperReport) JRLoader.loadObject(PuntoVenta.class.getResource("/reportes/report_Factura.jasper"));
            Map parametros = new HashMap<>();
            parametros.put("id", txtFac);
            JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    public void LimpiarDatosProdFact() {
        //Funcion para limpiar los text field existentes
        try {
            txt_cliente_f.setText("");
            txt_rnc_f.setText("");
            txt_vendedor_f.setText("");
            txt_total_f.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error " + ex);
        }
    }

    public float suma() {
        int contar = tbl_detalle.getRowCount();
        int total = 0;
        for (int i = 0; i < contar; i++) {
            total = total + Integer.parseInt(tbl_detalle.getValueAt(i, 4).toString());
        }
        return total;
    }

    private boolean RevisarStock(int idprod, int cantidad) {

        PreparedStatement ps;
        ResultSet rs;
        boolean checkStock = false;
        String query = "SELECT stock_disponible FROM ctrl_productos WHERE stock_disponible > ? AND idctrl_productos = ?";

        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setInt(1, cantidad);
            ps.setInt(2, idprod);
            rs = ps.executeQuery();
            if (rs.next()) {
                checkStock = true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
        return checkStock;

    }

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed

        int importe = Integer.parseInt(txt_precio_f.getText()) * Integer.parseInt(String.valueOf(Integer.parseInt(txt_cantidad_f.getText())));

        detalle[0] = lbl_no_f.getText();
        detalle[1] = txt_producto_f.getText();
        detalle[2] = txt_precio_f.getText();
        detalle[3] = txt_cantidad_f.getText();
        detalle[4] = importe;

        detalle_factura.addRow(detalle);

        txt_total_f.setText(String.valueOf(suma()));

        for (int i = 0; i < detalle.length; i++) {
            detalle[i] = "";
        }
        LimpiarDatosProd();


    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        pantalla_producto s = new pantalla_producto();
        s.setVisible(true);
        s.pack();
        s.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        int id_fact = Integer.parseInt(lbl_no_f.getText());

        String cli = txt_cliente_f.getText();
        String empleado = txt_vendedor_f.getText();
        String RNC = txt_rnc_f.getText();
        String total = txt_total_f.getText();

        PreparedStatement psf;
        String query = "INSERT INTO `factura`(`RNC`,`nombre_cliente`,`nombre_empleado`,`Total`) VALUES (?,?,?,?)";
        try {
            psf = MyConnection.getConnection().prepareStatement(query);

            psf.setString(1, RNC);
            psf.setString(2, cli);
            psf.setString(3, empleado);
            psf.setString(4, total);

            if (psf.executeUpdate() > 0) {

                PreparedStatement ps;
                for (int i = 0; i < tbl_detalle.getRowCount(); i++) {

                    String nombre_ = (tbl_detalle.getValueAt(i, 1).toString());
                    int precio_unit = Integer.parseInt(tbl_detalle.getValueAt(i, 2).toString());
                    int cant = Integer.parseInt(tbl_detalle.getValueAt(i, 3).toString());
                    int importe = Integer.parseInt(tbl_detalle.getValueAt(i, 4).toString());
                    String query_ = "INSERT INTO `detalle_factura`(`id_factura`,`nombre_producto`,`precio_unitario`,`cantidad`,`importe`) VALUES (?,?,?,?,?)";
                    try {
                        ps = MyConnection.getConnection().prepareStatement(query_);

                        ps.setInt(1, id_fact);
                        ps.setString(2, nombre_);
                        ps.setInt(3, precio_unit);
                        ps.setInt(4, cant);
                        ps.setInt(5, importe);

                        if (ps.executeUpdate() > 0) {

                        }
                        imprimir();
                    } catch (SQLException ex) {
                        Logger.getLogger(PuntoVenta.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "error: " + ex);
                    }

                }
                JOptionPane.showMessageDialog(null, "Factura Guardada.");
                LimpiarDatosProdFact();
                LimpiarDatosProd();
                Mostrardatos("");
                generarIdFact();
                SetFacturaID();

            }

        } catch (SQLException ex) {
            Logger.getLogger(PuntoVenta.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error " + ex);
        }
    }//GEN-LAST:event_btn_finalizarActionPerformed

    private void txt_cantidad_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidad_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidad_fActionPerformed

    private void btn_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar1ActionPerformed
        pantalla_empleados s = new pantalla_empleados();
        s.setVisible(true);
        s.pack();
        s.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_buscar1ActionPerformed

    private void txt_rnc_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rnc_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rnc_fActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuntoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PuntoVenta().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscar1;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cantidad_f;
    private javax.swing.JLabel lbl_cliente_f;
    private javax.swing.JLabel lbl_no_f;
    private javax.swing.JLabel lbl_no_f1;
    private javax.swing.JLabel lbl_no_factura;
    private javax.swing.JLabel lbl_no_factura1;
    private javax.swing.JLabel lbl_precio_f;
    private javax.swing.JLabel lbl_producto_f;
    private javax.swing.JLabel lbl_rnc_f;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_vendedor_f;
    private javax.swing.JTable tbl_detalle;
    private javax.swing.JTextField txt_cantidad_f;
    private javax.swing.JTextField txt_cliente_f;
    public static javax.swing.JTextField txt_precio_f;
    public static javax.swing.JTextField txt_producto_f;
    private javax.swing.JTextField txt_rnc_f;
    private javax.swing.JTextField txt_total_f;
    public static javax.swing.JTextField txt_vendedor_f;
    // End of variables declaration//GEN-END:variables

}
